spring.application.name=dang
spring.devtools.livereload.enabled=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.datasource.url=jdbc:postgresql://localhost:5432/hqtrivia
spring.datasource.username=postgres
spring.datasource.password=25092002cpr
spring.datasource.driver-class-name=org.postgresql.Driver

# create and drop table, good for testing, production set to none or comment it
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.api-docs.path=/api-docs
